[package]
name = "askcommand"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
serde_json = "1.0"
async-openai = "0.16.3"
tokio = { version = "1.33.0", features = ["full"] }